"""Initial

Revision ID: 27917e2442f7
Revises: 6dbc7d9d3736
Create Date: 2023-04-05 18:38:35.810441

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '27917e2442f7'
down_revision = '6dbc7d9d3736'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
